staging-settings:
  user-workflow:
    workflow-name: "folio-collar-oracle-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: "../secrets.yaml"

production-settings:
  user-workflow:
    workflow-name: "folio-collar-oracle-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: "../secrets.yaml"
